// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("CurrentInfo");

function make(currentPatient, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              if (currentPatient !== undefined) {
                var currentPatient$1 = currentPatient;
                return React.createElement("div", {
                            className: "currentInfo"
                          }, Caml_array.caml_array_get($$Array.of_list(currentPatient$1[/* names */1]), 0)[/* family */0] + (" @ " + (Caml_array.caml_array_get($$Array.of_list(currentPatient$1[/* addresses */2]), 0)[/* city */0] + (", " + Caml_array.caml_array_get($$Array.of_list(currentPatient$1[/* addresses */2]), 0)[/* state */1]))));
              } else {
                return React.createElement("div", {
                            className: "currentInfo"
                          });
              }
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
