// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Utils$ReactTemplate = require("../shared/Utils.bs.js");
var FormButtons$ReactTemplate = require("../shared/FormButtons.bs.js");

var component = ReasonReact.reducerComponent("NewPatient");

function make(onSave, onCancel, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", undefined, React.createElement("input", {
                              value: self[/* state */1][/* name */0],
                              onChange: (function (evt) {
                                  return Curry._1(self[/* send */3], /* OnChange */[Utils$ReactTemplate.valueFromEvent(evt)]);
                                })
                            }), ReasonReact.element(undefined, undefined, FormButtons$ReactTemplate.make((function () {
                                    return Curry._1(onSave, self[/* state */1][/* name */0]);
                                  }), (function () {
                                    return Curry._1(onCancel, /* () */0);
                                  }), undefined, /* array */[])));
            }),
          /* initialState */(function () {
              return /* record */[/* name */""];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _) {
              return /* Update */Block.__(0, [/* record */[/* name */action[0]]]);
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
