// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var NoteForm$ReactTemplate = require("./notes/NoteForm.bs.js");
var CommentsBox$ReactTemplate = require("./comments/CommentsBox.bs.js");
var NoteSelector$ReactTemplate = require("./notes/NoteSelector.bs.js");

var component = ReasonReact.statelessComponent("Assessment");

function make(currentPatient, user, patientComments, addComment, addNote, patientNotes, currentNote, switchNote, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "assessment"
                        }, React.createElement("div", {
                              className: "soapHeader"
                            }, "Assessment"), ReasonReact.element(undefined, undefined, CommentsBox$ReactTemplate.make(user, patientComments, currentPatient, addComment, /* array */[])), ReasonReact.element(undefined, undefined, NoteSelector$ReactTemplate.make(patientNotes, switchNote, /* array */[])), ReasonReact.element(undefined, undefined, NoteForm$ReactTemplate.make(user, currentPatient, currentNote, patientNotes, addNote, /* array */[])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
