// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

var fakeData = (require('../../FHIRdata.json'));

function nameDecoder(json) {
  return /* record */[
          /* family */Json_decode.field("family", Json_decode.string, json),
          /* given */Json_decode.field("given", (function (param) {
                  return Json_decode.array(Json_decode.string, param);
                }), json),
          /* text */Json_decode.optional((function (param) {
                  return Json_decode.field("text", Json_decode.string, param);
                }), json)
        ];
}

function addressDecoder(json) {
  return /* record */[
          /* city */Json_decode.field("city", Json_decode.string, json),
          /* state */Json_decode.field("state", Json_decode.string, json)
        ];
}

function patientDecoder(json) {
  return /* record */[
          /* pid */Json_decode.field("id", Json_decode.string, json),
          /* names */Json_decode.field("name", (function (param) {
                  return Json_decode.list(nameDecoder, param);
                }), json),
          /* addresses */Json_decode.field("address", (function (param) {
                  return Json_decode.list(addressDecoder, param);
                }), json)
        ];
}

function practitionerDecoder(json) {
  return /* record */[
          /* practitionerId */Json_decode.field("id", Json_decode.string, json),
          /* practitionerNames */Json_decode.field("name", (function (param) {
                  return Json_decode.list(nameDecoder, param);
                }), json)
        ];
}

function itemDecoder(json) {
  return /* record */[/* ref */Json_decode.field("reference", Json_decode.string, json)];
}

function entryDecoder(json) {
  return /* record */[/* item */Json_decode.field("item", itemDecoder, json)];
}

function teamDecoder(json) {
  return /* record */[
          /* teamId */Json_decode.field("id", Json_decode.string, json),
          /* title */Json_decode.field("title", Json_decode.string, json),
          /* items */Json_decode.field("entry", (function (param) {
                  return Json_decode.list(entryDecoder, param);
                }), json)
        ];
}

function clinicalImpressionDecoder(json) {
  return /* record */[
          /* clinicalImpressionId */Json_decode.field("id", Json_decode.string, json),
          /* description */Json_decode.field("description", Json_decode.string, json),
          /* summary */Json_decode.field("summary", Json_decode.string, json),
          /* dateTime */Json_decode.field("date", Json_decode.date, json),
          /* assessor */Json_decode.field("assessor", itemDecoder, json),
          /* subject */Json_decode.field("subject", itemDecoder, json)
        ];
}

function codeDecoder(json) {
  return /* record */[/* code */Json_decode.field("code", Json_decode.string, json)];
}

function codingDecoder(json) {
  return /* record */[/* coding */Json_decode.field("coding", (function (param) {
                  return Json_decode.list(codeDecoder, param);
                }), json)];
}

function observationDecoder(json) {
  return /* record */[
          /* observationId */Json_decode.field("id", Json_decode.string, json),
          /* category */Json_decode.field("category", (function (param) {
                  return Json_decode.list(codingDecoder, param);
                }), json),
          /* code */Json_decode.field("code", codingDecoder, json),
          /* subject */Json_decode.field("subject", itemDecoder, json),
          /* value */Json_decode.field("valueString", Json_decode.string, json)
        ];
}

function dataDecoder(json) {
  return /* record */[
          /* patients */Json_decode.field("patient", (function (param) {
                  return Json_decode.list(patientDecoder, param);
                }), json),
          /* practitioners */Json_decode.field("practitioner", (function (param) {
                  return Json_decode.list(practitionerDecoder, param);
                }), json),
          /* teams */Json_decode.field("list", (function (param) {
                  return Json_decode.list(teamDecoder, param);
                }), json),
          /* clinicalImpressions */Json_decode.field("clinicalImpression", (function (param) {
                  return Json_decode.list(clinicalImpressionDecoder, param);
                }), json),
          /* observations */Json_decode.field("observation", (function (param) {
                  return Json_decode.list(observationDecoder, param);
                }), json)
        ];
}

var data = dataDecoder(fakeData);

exports.fakeData = fakeData;
exports.nameDecoder = nameDecoder;
exports.addressDecoder = addressDecoder;
exports.patientDecoder = patientDecoder;
exports.practitionerDecoder = practitionerDecoder;
exports.itemDecoder = itemDecoder;
exports.entryDecoder = entryDecoder;
exports.teamDecoder = teamDecoder;
exports.clinicalImpressionDecoder = clinicalImpressionDecoder;
exports.codeDecoder = codeDecoder;
exports.codingDecoder = codingDecoder;
exports.observationDecoder = observationDecoder;
exports.dataDecoder = dataDecoder;
exports.data = data;
/* fakeData Not a pure module */
