// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

function valueFromEvent(evt) {
  return evt.target.value;
}

function extractId(refString) {
  var refLength = refString.length;
  var idIndex = $$String.index(refString, /* "/" */47) + 1 | 0;
  var idLength = refLength - idIndex | 0;
  return $$String.sub(refString, idIndex, idLength);
}

exports.valueFromEvent = valueFromEvent;
exports.extractId = extractId;
/* No side effect */
