// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var NoteAssembler$ReactTemplate = require("./NoteAssembler.bs.js");

((require('../styles.css')));

var jsComponent = ReasonReact.wrapReasonForJs(NoteAssembler$ReactTemplate.component, (function (jsProps) {
        return NoteAssembler$ReactTemplate.make(undefined, Js_primitive.some(jsProps.storage), /* array */[]);
      }));

exports.jsComponent = jsComponent;
/*  Not a pure module */
