// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReactContext = require("reason-react-context/src/ReasonReactContext.bs.js");

var Context = ReasonReactContext.CreateContext(/* module */[
      /* name */"Storage",
      /* defaultValue */undefined
    ]);

exports.Context = Context;
/* Context Not a pure module */
